# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Research"
  url = "menu-projects/"
  weight = 30

[[main]]
  name = "People"
  url = "menu-group-members/"
  weight=40

[[main]]
  name = "Publications"
  url = "publication/"
  weight = 80

[[main]]
  name = "Resources"
  weight = 90

# [[main]]
#   parent = "Resources"
#   name = "Mind bytes"
#   url = "resources/mind-bytes/"
#   weight = 92

# [[main]]
#   parent = "Resources"
#   name = "Courses"
#   weight = 94
#   hidden = true

[[main]]
  parent = "Resources"
  name = "Downloads"
  url = "resources/downloads"
  weight = 96

[[main]]
  parent = "Resources"
  name = "Links"
  url = "resources/links"
  weight = 98

[[main]]
  name = "Contact"
  url = "contact/"
  weight = 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
